# Generated by Django 5.2.15 on 2026-06-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_professionnel_date_embauche'),
        ('establishments', '0005_etablissement_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('duree', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(default='confirme', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='authentication.client')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='establishments.prestation')),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='authentication.professionnel')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_heure'],
            },
        ),
    ]
