# Generated by Django 5.2.15 on 2026-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(default='on_site', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=50),
        ),
    ]
