# Generated by Django 5.2.15 on 2026-06-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
