# Generated by Django 5.2.15 on 2026-06-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_reservation_payment_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
