# Generated by Django 5.2.15 on 2026-06-20 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_professionnel_date_embauche'),
        ('bookings', '0004_reservation_stripe_session_id'),
        ('establishments', '0009_remove_etablissement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=255)),
                ('prestation_nom', models.CharField(max_length=255)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reservation', models.DateTimeField()),
                ('payment_status', models.CharField(default='paid', max_length=50)),
                ('reference', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='authentication.client')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='establishments.etablissement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
    ]
