# Generated by Django 5.2.15 on 2026-06-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerant',
            name='etablissement',
        ),
    ]
