# Generated by Django 5.2.15 on 2026-06-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_gerant_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnel',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
