# Generated by Django 5.2.15 on 2026-06-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_secteur_etablissement_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='adresse',
        ),
    ]
