# Generated by Django 5.2.15 on 2026-06-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_gerant_etablissement'),
        ('establishments', '0003_remove_etablissement_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='gerant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='authentication.gerant'),
        ),
    ]
