# Generated by Django 5.2.15 on 2026-06-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_etablissement_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='horaires',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='nombre_avis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='note_accueil',
            field=models.DecimalField(decimal_places=1, default=4.7, max_digits=2),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='note_cadre',
            field=models.DecimalField(decimal_places=1, default=4.7, max_digits=2),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='note_globale',
            field=models.DecimalField(decimal_places=1, default=4.7, max_digits=2),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='note_prestation',
            field=models.DecimalField(decimal_places=1, default=4.7, max_digits=2),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='note_proprete',
            field=models.DecimalField(decimal_places=1, default=4.7, max_digits=2),
        ),
    ]
