# Generated by Django 5.2.15 on 2026-06-20 14:33

import establishments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0006_etablissement_horaires_etablissement_nombre_avis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='horaires',
            field=models.JSONField(blank=True, default=establishments.models.default_horaires, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='note_accueil',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='note_cadre',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='note_globale',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='note_prestation',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='note_proprete',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
