# Generated by Django 5.2.15 on 2026-06-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0007_alter_etablissement_horaires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='region',
        ),
    ]
