# Generated by Django 5.2.15 on 2026-06-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0008_remove_lieu_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='status',
        ),
    ]
