# Generated by Django 5.2.15 on 2026-06-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_professionnel_date_embauche'),
        ('establishments', '0009_remove_etablissement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='prestation',
            name='collaborateurs',
            field=models.ManyToManyField(blank=True, related_name='prestations', to='authentication.professionnel'),
        ),
    ]
