name: Deploy to Production (Debian 13 VM)

on:
  push:
    branches:
      - prod
jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted # Exécute le déploiement directement sur votre VM Debian

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy and rebuild production Docker containers
        run: |
          echo "Démarrage du déploiement..."
          # Aller dans le dossier du projet sur la VM (remplacez ~/timely par votre chemin exact si nécessaire)
          cd ~/timely
          
          # Tirer le dernier code de la branche prod
          git pull origin prod
          
          # Recompiler et relancer la stack
          docker compose -f docker-compose.prod.yml up --build -d
          
          echo "Déploiement terminé avec succès !"
